# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: heipacker 三两地
email: heipackermail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
闲来无事， 找个地方吐吐槽， 看官见谅。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://heipacker.github.io/" # the base hostname & protocol for your site
twitter_username: heipacker
github_username:  heipacker

# Build settings
markdown: kramdown
gems:
          - jekyll-gist
